name: weather_app
description: "Wettervorhersage-App mit erweiterten Funktionen und schöner UI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.70.0
  intl: ^0.20.1
  provider: ^6.0.0
  geolocator: ^13.0.2
  sqflite: ^2.0.0
  path: ^1.8.2

dev_dependencies:
  mockito: ^5.4.5
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
